apiVersion: v1
kind: ConfigMap
metadata:
  name: disaster-config
  namespace: disaster-platform
data:
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC_RAW: "sensor-raw"
  KAFKA_TOPIC_ALERTS: "alerts"
  KAFKA_TOPIC_PREDICTIONS: "predictions"
  PORT: "8080"
  ENVIRONMENT: "production"
  AWS_REGION: "ap-south-1"
